from __future__ import annotations

import golf_ball_plotter_svg_gcode_runner as legacy


RUNTIME_KEYS = [
    "SERIAL_PORT",
    "BAUD_RATE",
    "MOTOR_FULL_STEPS_PER_REV",
    "X_MICROSTEPS",
    "Y_MICROSTEPS",
    "X_DRAW_MIN",
    "X_DRAW_MAX",
    "Y_DRAW_MIN",
    "Y_DRAW_MAX",
    "BALL_CENTER_X",
    "BALL_CENTER_Y",
    "BALL_DIAMETER_MM",
    "DEFAULT_X_MAX_FEED",
    "DEFAULT_Y_MAX_FEED",
    "DEFAULT_X_ACCELERATION",
    "DEFAULT_Y_ACCELERATION",
    "DEFAULT_DRAW_FEED",
    "DEFAULT_TRAVEL_FEED",
    "DEFAULT_LINE_THICKNESS_MM",
    "DEFAULT_PEN_UP_S",
    "DEFAULT_PEN_DOWN_S",
    "DEFAULT_SERVO_DWELL",
    "DEFAULT_SERVO_RAMP_ENABLED",
    "DEFAULT_SERVO_RAMP_STEP",
    "DEFAULT_SERVO_RAMP_DELAY_MS",
    "DEFAULT_PEN_UP_DWELL_MS",
    "DEFAULT_PEN_DOWN_DWELL_MS",
    "MIN_SERVO_S",
    "MAX_SERVO_S",
    "DEFAULT_SAMPLE_STEP_DEG",
    "DEFAULT_CURVE_SAMPLES",
    "DEFAULT_MARGIN_PERCENT",
    "DEFAULT_ROTATION_DEG",
    "DEFAULT_ENABLE_FILL",
    "DEFAULT_FILL_MODE",
    "DEFAULT_PARSER_MODE",
    "DEFAULT_COLOR_MAPPING_MODE",
    "DEFAULT_TRACE_STROKE_ONLY_PATHS",
    "DEFAULT_FILL_ONLY_DARK_SVG_FILLS",
    "DEFAULT_WALL_COUNT",
    "DEFAULT_INFILL_PATTERN",
    "DEFAULT_INFILL_DENSITY",
    "DEFAULT_INFILL_SPACING_MM",
    "DEFAULT_INFILL_ANGLE_DEG",
    "DEFAULT_OUTLINE_AFTER_FILL",
    "DEFAULT_MIN_FILL_AREA_MM2",
    "DEFAULT_MIN_FILL_WIDTH_MM",
    "DEFAULT_SIMPLIFY_TOLERANCE_MM",
    "DEFAULT_REMOVE_DUPLICATE_PATHS",
    "DEFAULT_SMALL_SHAPE_MODE",
    "DEFAULT_MIN_SEGMENT_LENGTH_MM",
    "DEFAULT_TRAVEL_OPTIMIZATION",
    "SVG_DARK_FILL_LUMINANCE_THRESHOLD",
    "SVG_LIGHT_CUTOUT_LUMINANCE_THRESHOLD",
    "SVG_MIN_PRINT_OPACITY",
]


def configure_runtime(config, state_dict, serial_lock):
    for key in RUNTIME_KEYS:
        if key in config:
            setattr(legacy, key, config[key])
    legacy.X_STEPS_PER_DEGREE = (config["MOTOR_FULL_STEPS_PER_REV"] * config["X_MICROSTEPS"]) / 360.0
    legacy.Y_STEPS_PER_DEGREE = (config["MOTOR_FULL_STEPS_PER_REV"] * config["Y_MICROSTEPS"]) / 360.0
    legacy.state = state_dict
    legacy.serial_lock = serial_lock
    return legacy
