from __future__ import annotations

import os


def _env_bool(name: str, default: bool) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _env_int(name: str, default: int) -> int:
    try:
        return int(os.getenv(name, default))
    except (TypeError, ValueError):
        return default


def _env_float(name: str, default: float) -> float:
    try:
        return float(os.getenv(name, default))
    except (TypeError, ValueError):
        return default


class Config:
    SECRET_KEY = os.getenv("SECRET_KEY", "dev")
    MAX_CONTENT_LENGTH = _env_int("MAX_CONTENT_LENGTH", 2 * 1024 * 1024)

    FLASK_HOST = os.getenv("FLASK_HOST", "127.0.0.1")
    FLASK_PORT = _env_int("FLASK_PORT", 5000)
    FLASK_DEBUG = _env_bool("FLASK_DEBUG", False)

    SERIAL_PORT = os.getenv("SERIAL_PORT", "COM12")
    BAUD_RATE = _env_int("BAUD_RATE", 115200)

    MOTOR_FULL_STEPS_PER_REV = _env_int("MOTOR_FULL_STEPS_PER_REV", 200)
    X_MICROSTEPS = _env_int("X_MICROSTEPS", 16)
    Y_MICROSTEPS = _env_int("Y_MICROSTEPS", 16)

    X_DRAW_MIN = _env_float("X_DRAW_MIN", -180.0)
    X_DRAW_MAX = _env_float("X_DRAW_MAX", 180.0)
    Y_DRAW_MIN = _env_float("Y_DRAW_MIN", -45.0)
    Y_DRAW_MAX = _env_float("Y_DRAW_MAX", 45.0)

    BALL_CENTER_X = _env_float("BALL_CENTER_X", 0.0)
    BALL_CENTER_Y = _env_float("BALL_CENTER_Y", 0.0)
    BALL_DIAMETER_MM = _env_float("BALL_DIAMETER_MM", 42.67)

    DEFAULT_X_MAX_FEED = _env_float("DEFAULT_X_MAX_FEED", 6000.0)
    DEFAULT_Y_MAX_FEED = _env_float("DEFAULT_Y_MAX_FEED", 6000.0)
    DEFAULT_X_ACCELERATION = _env_float("DEFAULT_X_ACCELERATION", 100.0)
    DEFAULT_Y_ACCELERATION = _env_float("DEFAULT_Y_ACCELERATION", 100.0)
    DEFAULT_DRAW_FEED = _env_float("DEFAULT_DRAW_FEED", 1200.0)
    DEFAULT_TRAVEL_FEED = _env_float("DEFAULT_TRAVEL_FEED", 3000.0)
    DEFAULT_LINE_THICKNESS_MM = _env_float("DEFAULT_LINE_THICKNESS_MM", 0.2)

    DEFAULT_PEN_UP_S = _env_int("DEFAULT_PEN_UP_S", 575)
    DEFAULT_PEN_DOWN_S = _env_int("DEFAULT_PEN_DOWN_S", 700)
    DEFAULT_SERVO_DWELL = _env_float("DEFAULT_SERVO_DWELL", 0.06)
    DEFAULT_SERVO_RAMP_ENABLED = _env_bool("DEFAULT_SERVO_RAMP_ENABLED", True)
    DEFAULT_SERVO_RAMP_STEP = _env_int("DEFAULT_SERVO_RAMP_STEP", 20)
    DEFAULT_SERVO_RAMP_DELAY_MS = _env_float("DEFAULT_SERVO_RAMP_DELAY_MS", 10.0)
    DEFAULT_PEN_UP_DWELL_MS = _env_float("DEFAULT_PEN_UP_DWELL_MS", 30.0)
    DEFAULT_PEN_DOWN_DWELL_MS = _env_float("DEFAULT_PEN_DOWN_DWELL_MS", 60.0)
    MOTOR_HOLD_ENABLED_AFTER_CALIBRATION = _env_bool("MOTOR_HOLD_ENABLED_AFTER_CALIBRATION", True)
    STEPPER_RELEASE_IDLE_DELAY_VALUE = _env_int("STEPPER_RELEASE_IDLE_DELAY_VALUE", 0)
    STEPPER_HOLD_IDLE_DELAY_VALUE = _env_int("STEPPER_HOLD_IDLE_DELAY_VALUE", 255)
    STEPPER_HOLD_ENGAGE_DELTA_DEG = _env_float("STEPPER_HOLD_ENGAGE_DELTA_DEG", 0.25)
    STEPPER_HOLD_ENGAGE_FEED = _env_float("STEPPER_HOLD_ENGAGE_FEED", 120.0)
    DEFAULT_GCODE_MODE = os.getenv("DEFAULT_GCODE_MODE", "simple")
    MIN_SERVO_S = _env_int("MIN_SERVO_S", 500)
    MAX_SERVO_S = _env_int("MAX_SERVO_S", 1000)

    DEFAULT_SAMPLE_STEP_DEG = _env_float("DEFAULT_SAMPLE_STEP_DEG", 1.0)
    DEFAULT_MAX_PRINT_X_SPAN_DEG = _env_float("DEFAULT_MAX_PRINT_X_SPAN_DEG", 120.0)
    DEFAULT_IGNORE_PRINTABLE_X_SPAN_LIMIT = _env_bool("DEFAULT_IGNORE_PRINTABLE_X_SPAN_LIMIT", False)
    DEFAULT_CURVE_SAMPLES = _env_int("DEFAULT_CURVE_SAMPLES", 80)
    DEFAULT_MARGIN_PERCENT = _env_float("DEFAULT_MARGIN_PERCENT", 4.0)
    DEFAULT_ROTATION_DEG = _env_float("DEFAULT_ROTATION_DEG", 0.0)
    DEFAULT_ENABLE_FILL = _env_bool("DEFAULT_ENABLE_FILL", True)
    DEFAULT_FILL_MODE = os.getenv("DEFAULT_FILL_MODE", "slicer")
    DEFAULT_PARSER_MODE = os.getenv("DEFAULT_PARSER_MODE", "visible_geometry")
    DEFAULT_COLOR_MAPPING_MODE = _env_bool("DEFAULT_COLOR_MAPPING_MODE", False)
    DEFAULT_TRACE_STROKE_ONLY_PATHS = _env_bool("DEFAULT_TRACE_STROKE_ONLY_PATHS", True)
    DEFAULT_FILL_ONLY_DARK_SVG_FILLS = _env_bool("DEFAULT_FILL_ONLY_DARK_SVG_FILLS", True)
    DEFAULT_WALL_COUNT = _env_int("DEFAULT_WALL_COUNT", 1)
    DEFAULT_INFILL_PATTERN = os.getenv("DEFAULT_INFILL_PATTERN", "hatch")
    DEFAULT_INFILL_DENSITY = _env_float("DEFAULT_INFILL_DENSITY", 100.0)
    DEFAULT_INFILL_SPACING_MM = _env_float("DEFAULT_INFILL_SPACING_MM", 0.48)
    DEFAULT_INFILL_ANGLE_DEG = _env_float("DEFAULT_INFILL_ANGLE_DEG", 45.0)
    DEFAULT_FILL_STRATEGY = os.getenv("DEFAULT_FILL_STRATEGY", "adaptive_angle")
    DEFAULT_ALTERNATE_FILL_ANGLE_DEG = _env_float("DEFAULT_ALTERNATE_FILL_ANGLE_DEG", -45.0)
    DEFAULT_OUTLINE_AFTER_FILL = _env_bool("DEFAULT_OUTLINE_AFTER_FILL", True)
    DEFAULT_MIN_FILL_AREA_MM2 = _env_float("DEFAULT_MIN_FILL_AREA_MM2", 1.0)
    DEFAULT_MIN_FILL_WIDTH_MM = _env_float("DEFAULT_MIN_FILL_WIDTH_MM", 0.2)
    DEFAULT_SIMPLIFY_TOLERANCE_MM = _env_float("DEFAULT_SIMPLIFY_TOLERANCE_MM", 0.05)
    DEFAULT_REMOVE_DUPLICATE_PATHS = _env_bool("DEFAULT_REMOVE_DUPLICATE_PATHS", True)
    DEFAULT_SMALL_SHAPE_MODE = os.getenv("DEFAULT_SMALL_SHAPE_MODE", "single-wall")
    DEFAULT_THIN_DETAIL_MODE = _env_bool("DEFAULT_THIN_DETAIL_MODE", True)
    DEFAULT_THIN_DETAIL_MIN_AREA_MM2 = _env_float("DEFAULT_THIN_DETAIL_MIN_AREA_MM2", 0.05)
    DEFAULT_THIN_DETAIL_SIMPLIFY_MM = _env_float("DEFAULT_THIN_DETAIL_SIMPLIFY_MM", 0.1)
    DEFAULT_THIN_DETAIL_OVERLAP = _env_bool("DEFAULT_THIN_DETAIL_OVERLAP", True)
    DEFAULT_MIN_SEGMENT_LENGTH_MM = _env_float("DEFAULT_MIN_SEGMENT_LENGTH_MM", 0.5)
    DEFAULT_TRAVEL_OPTIMIZATION = os.getenv("DEFAULT_TRAVEL_OPTIMIZATION", "nearest-neighbor")
    DEFAULT_ALLOW_PEN_DOWN_INFILL_CONNECTORS = _env_bool("DEFAULT_ALLOW_PEN_DOWN_INFILL_CONNECTORS", True)
    DEFAULT_INFILL_PATH_MODE = os.getenv("DEFAULT_INFILL_PATH_MODE", "rectilinear")
    ALLOW_DETAIL_OVERLAP_OUTLINE = _env_bool("ALLOW_DETAIL_OVERLAP_OUTLINE", True)
    DETAIL_VALIDATE_WITH_PEN_FOOTPRINT = _env_bool("DETAIL_VALIDATE_WITH_PEN_FOOTPRINT", True)
    MAX_DETAIL_OVERSPILL_MM = _env_float("MAX_DETAIL_OVERSPILL_MM", 0.05)
    MAX_DETAIL_OVERSPILL_AREA_RATIO = _env_float("MAX_DETAIL_OVERSPILL_AREA_RATIO", 0.03)
    MIN_DETAIL_COVERAGE_GAIN_RATIO = _env_float("MIN_DETAIL_COVERAGE_GAIN_RATIO", 0.15)
    ALLOW_DETAIL_PEN_DOWN_CONTINUATION = _env_bool("ALLOW_DETAIL_PEN_DOWN_CONTINUATION", True)
    MAX_DETAIL_CONTINUATION_LENGTH_MM = _env_float("MAX_DETAIL_CONTINUATION_LENGTH_MM", 0.0)
    PREFERRED_DETAIL_CONTINUATION_LENGTH_MM = _env_float("PREFERRED_DETAIL_CONTINUATION_LENGTH_MM", 0.0)
    MAX_DETAIL_CONTINUATION_OVERSPILL_MM = _env_float("MAX_DETAIL_CONTINUATION_OVERSPILL_MM", 0.05)
    MAX_DETAIL_CONTINUATION_OVERSPILL_AREA_RATIO = _env_float("MAX_DETAIL_CONTINUATION_OVERSPILL_AREA_RATIO", 0.02)
    MAX_DETAIL_CONTINUATION_TURN_DEG = _env_float("MAX_DETAIL_CONTINUATION_TURN_DEG", 120.0)
    ALLOW_DETAIL_TRACE_MERGING = _env_bool("ALLOW_DETAIL_TRACE_MERGING", True)
    MAX_DETAIL_MERGE_GAP_MM = _env_float("MAX_DETAIL_MERGE_GAP_MM", 0.0)
    PREFERRED_DETAIL_MERGE_GAP_MM = _env_float("PREFERRED_DETAIL_MERGE_GAP_MM", 0.0)
    MAX_DETAIL_MERGE_TURN_DEG = _env_float("MAX_DETAIL_MERGE_TURN_DEG", 135.0)
    GCODE_COLLINEAR_MERGE_ENABLED = _env_bool("GCODE_COLLINEAR_MERGE_ENABLED", True)
    COLLINEAR_ANGLE_TOLERANCE_DEG = _env_float("COLLINEAR_ANGLE_TOLERANCE_DEG", 1.0)
    COLLINEAR_DISTANCE_TOLERANCE_MM = _env_float("COLLINEAR_DISTANCE_TOLERANCE_MM", 0.02)
    MIN_OUTPUT_SEGMENT_LENGTH_MM = _env_float("MIN_OUTPUT_SEGMENT_LENGTH_MM", 0.05)
    DEFAULT_THIN_REGION_SINGLE_STROKE_MAX_FACTOR = _env_float("DEFAULT_THIN_REGION_SINGLE_STROKE_MAX_FACTOR", 1.5)
    DEFAULT_NARROW_REGION_MAX_FACTOR = _env_float("DEFAULT_NARROW_REGION_MAX_FACTOR", 3.0)
    DEFAULT_COLLAPSE_OUTLINE_MAX_FACTOR = _env_float("DEFAULT_COLLAPSE_OUTLINE_MAX_FACTOR", 2.0)
    DEFAULT_TINY_DOT_AREA_FACTOR = _env_float("DEFAULT_TINY_DOT_AREA_FACTOR", 0.20)
    DEFAULT_SINGLE_STROKE_WIDTH_MAX_FACTOR = _env_float("DEFAULT_SINGLE_STROKE_WIDTH_MAX_FACTOR", 1.15)
    DEFAULT_CENTERLINE_WIDTH_MAX_FACTOR = _env_float("DEFAULT_CENTERLINE_WIDTH_MAX_FACTOR", 1.5)
    DEFAULT_DETAIL_WIDTH_MAX_FACTOR = _env_float("DEFAULT_DETAIL_WIDTH_MAX_FACTOR", 2.5)
    DEFAULT_STREAMING_MODE = os.getenv("DEFAULT_STREAMING_MODE", "buffered")
    DEFAULT_RASTER_MAX_COLORS = _env_int("DEFAULT_RASTER_MAX_COLORS", 32)
    DEFAULT_RASTER_COLOR_TOLERANCE = _env_int("DEFAULT_RASTER_COLOR_TOLERANCE", 24)
    DEFAULT_RASTER_MIN_COMPONENT_AREA_PX = _env_int("DEFAULT_RASTER_MIN_COMPONENT_AREA_PX", 8)
    DEFAULT_RASTER_MASK_OPEN_RADIUS_PX = _env_int("DEFAULT_RASTER_MASK_OPEN_RADIUS_PX", 0)
    DEFAULT_RASTER_MASK_CLOSE_RADIUS_PX = _env_int("DEFAULT_RASTER_MASK_CLOSE_RADIUS_PX", 1)
    DEFAULT_RASTER_MIN_REGION_AREA_PX = _env_float("DEFAULT_RASTER_MIN_REGION_AREA_PX", 16.0)
    DEFAULT_RASTER_REGION_SIMPLIFY_PX = _env_float("DEFAULT_RASTER_REGION_SIMPLIFY_PX", 1.0)
    RASTER_MASK_TRACE_SUPERSAMPLE = _env_int("RASTER_MASK_TRACE_SUPERSAMPLE", 4)
    RASTER_CONTOUR_SMOOTHING_PX = _env_float("RASTER_CONTOUR_SMOOTHING_PX", 0.35)
    RASTER_CURVE_FIT_TOLERANCE_PX = _env_float("RASTER_CURVE_FIT_TOLERANCE_PX", 0.25)

    SVG_DARK_FILL_LUMINANCE_THRESHOLD = _env_float("SVG_DARK_FILL_LUMINANCE_THRESHOLD", 0.42)
    SVG_LIGHT_CUTOUT_LUMINANCE_THRESHOLD = _env_float("SVG_LIGHT_CUTOUT_LUMINANCE_THRESHOLD", 0.82)
    SVG_MIN_PRINT_OPACITY = _env_float("SVG_MIN_PRINT_OPACITY", 0.99)
